### ISSUE TITLE
OpenBLAS is disabled by default

### ISSUE THREAD

**Issue by yoshipon** [QuantStack/xtensor-blas#37]
To enable OpenBLAS, it is necessary to 
1. add a compile flag `-DWITH_OPENBLAS`
2. copy `cxxstd` directory from FLENS repository

With these tips, the following code costs about 0.1 [s] in my computer whereas it costs 16 [s] without them:
```
template <size_t D> using xtsize = std::array<size_t, D>;

xt::xtensor<double, 2> a(xtsize<2>{2000, 2000}), b(xtsize<2>{2000, 2000});
xt::linalg::dot(a, b);
```
I would suggest to notice about `WITH_OPENBLAS` option in `README.md` with other blas options (such as `WITH_MKLBLAS`).

**Comment by SylvainCorlay** [comment]
Thanks, this would be a good improvement to the readme.md. Pull request welcome!

Note that the `conda` recipe is built against openblas.

**Comment by yoshipon** [comment]
Thank you for your information and suggestion.

I also compiled with `xtensor-blas` installed by conda.
However, I got the following error message:
`/anaconda2/include/cxxblas/drivers/openblas.h:36:28: fatal error: cxxstd/cstdlib.h: No such file or directory`
This can be solved by manually adding `cxxstd` directory from FLENS.

By removing the flag `-DWITH_OPENBLAS`, the above code can be compiled however it was slow.

**Comment by SylvainCorlay** [comment]
I am very surprised you would have an issue with the conda builds. 

For example, we use it here: [![Binder](https://img.shields.io/badge/launch-binder-brightgreen.svg)](https://beta.mybinder.org/v2/gh/QuantStack/xtensor/0.11.3?filepath=notebooks/xtensor.ipynb) without an issue.

If you are building on windows, this might also be a PATH issue.

**Comment by yoshipon** [comment]
This is because there are no errors if the FLENS is compiled without `-DWITH_OPENBLAS` flag.
Note that this flag is used in `cxxblas/drivers/drivers.h`.

I tested the following code on the above Binder:
```
#ifdef WITH_OPENBLAS
std::cout << "openBLAS is enabled";
#else
std::cout << "openBLAS is disabled";
#endif
```
and the result was "openBLAS is disabled".
I think openBLAS is disabled on the Binder.


I'm working on Ubutun 16.04 and maybe I correctly configured include paths.

**Comment by SylvainCorlay** [comment]
Thanks!

However it seems that we are using the openblas dlls since properly.

Cc @wolfv

**Comment by yoshipon** [comment]
Thank you again for your kindly replies.

I'm afraid that your compile could be done even when the openblas is not linked.
If the `WITH_OPENBLAS` flag is not set, FLENS automatically uses non-accelerated codes.
This is switched by `HAVE_BLAS` flag which is enabled by setting the `WITH_OPENBLAS` flag.

Please check `gemm_generic` is not called when executing the above code.
This is an alternative implementation that does not uses openblas and defined in `cxxblas/level3/gemm.tcc`
If openblas is enabled, the following function will be called:
```
template <typename IndexType>
typename If<IndexType>::isBlasCompatibleInteger
gemm(StorageOrder order,
     Transpose transA, Transpose transB,
     IndexType m, IndexType n, IndexType k,
     double alpha,
     const double *A, IndexType ldA,
     const double *B, IndexType ldB,
     double beta,
     double *C, IndexType ldC)
```

**Comment by SylvainCorlay** [comment]
I agree that there is definitely an issue here. I marked the issue as a "bug". Thank you for bringing this up!

For some reason, our tests are correctly linking with openblas, so I need to investigate what is going on.
![screenshot from 2017-09-25 19-53-14](https://user-images.githubusercontent.com/2397974/30823104-709d0842-a22b-11e7-8b70-83d571f8481a.png). Also, we tested various blas implementation and were seeing the differences in performance.

**Comment by yoshipon** [comment]
Thank you for your treatment.
I understand the tests are correctly linking with openblas and you have carefully tested.

The issue is considered that, for end-users (who installed `xtensor-blas `with conda), conda does not install the `cxxstd` directory, which is necessary to compile `xtensor-blas` with OpenBLAS.

**Comment by wolfv** [comment]
Hi, 

the way I understand it is that `cblas` is a library exposing BLAS functions to a C interface. cblas itself is (I think) vendored in the various BLAS implementations. E.g. MKL, ATLAS and OpenBLAS all ship a cblas header file.
We could use OpenBLAS directly (without going through cblas) but it would require the steps you mentioned. I'd rather not add `cxxstd` to our repository.

I think using the BLAS implementations will be as efficient as using the FLENS interface. I'll close the issue for now, but if there are objections I'm happy to reopen.

Cheers,

Wolf
